### ISSUE TITLE
Can you provide the docker image of arm32v7/erlang:21-alpine as soon as possible?

### ISSUE THREAD

**Issue by zhanghongtong** [erlang/docker-erlang-otp#188] opened 2018-12-11 09:06 UTC
Can you provide the docker image of ` arm32v7/erlang:21-alpine` as soon as possible in this [repository](https://hub.docker.com/r/arm32v7/erlang/)? Thank you

**Comment by c0b** [comment] 2018-12-11 18:34
I did a search of alpine tags on registry api, got this `amd64` `arm64` `386` `ppc64le` `s390x` 5 architectures only, and I believe we tried enable this `arm32v7` before but erlang C code failed to build on this architecture, it was on docker-hub's own CI system, and maintainers here do not have this hardware, so somewhere could not reproduce,

```console
$ curl -v https://registry-1.docker.io/v2/library/erlang/manifests/21-alpine -H ...   |   jq
< HTTP/1.1 200 OK
< Content-Length: 1694
< Content-Type: application/vnd.docker.distribution.manifest.list.v2+json
< Docker-Content-Digest: sha256:f51cff3784b1042cdda9f09878e41f204f66c7fedb862d3555d287e9d8bac1e0
< Docker-Distribution-Api-Version: registry/2.0
< Etag: "sha256:f51cff3784b1042cdda9f09878e41f204f66c7fedb862d3555d287e9d8bac1e0"
< Date: Tue, 11 Dec 2018 18:22:24 GMT
< Strict-Transport-Security: max-age=31536000
< 
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 740,
         "digest": "sha256:341091e2a13c422d13e4067cda97112624e3ae46f248935be379395e437135be",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 947,
         "digest": "sha256:b4656f184ad561754790b520148e1c798c68967769ecfbf2d53353dee698c675",
         "platform": {
            "architecture": "arm64",
            "os": "linux",
            "variant": "v8"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 947,
         "digest": "sha256:c348eb47afa29cccd2257ee81954b614389bf9ec568d1739ab4f30fa2e8e340d",
         "platform": {
            "architecture": "386",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 947,
         "digest": "sha256:96bf0c434da38472783e33aeff225c77947a53958d0fd829a972583686ba86e5",
         "platform": {
            "architecture": "ppc64le",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 947,
         "digest": "sha256:93eb0deabf21e9847aee014a8a8d3a0503224a36814016e81a49b132edfe0d61",
         "platform": {
            "architecture": "s390x",
            "os": "linux"
         }
      }
   ]
}
```

Read more on the Offcial-images doc:  https://github.com/docker-library/official-images#architectures-other-than-amd64

BTW,  it may not be good to ask some open source project to provide ...  as soon as possible
if someone happened to have the hardware resource and technical ability and have time, may do this by the way, for fun or something, that would be good, for your project and for this community

**Comment by zhanghongtong** [comment] 2018-12-12 01:20
Sorry, please forgive my offense.

**Comment by getong** [comment] 2019-03-20 12:35
It seems solved, close it.

**Closed by getong** 2019-03-20 12:35 UTC
